config:
    mongo_host: "localhost"
    mongo_port: 27017
    mongo_db: "dbname"
    mongo_user: "username"
    mongo_pwd: "password"
    server_host: "localhost"
    server_port: 8080
    notification:
        server_port: 8888
        pfx_file: 'apns.p12'
        pfx_passphrase: 'passphrase'

